### ISSUE TITLE
Aprendendo ElasticSearch

### ISSUE THREAD

**Issue by fernandoparanhos** [alexandreesl/livro-elasticsearch#5]
Boa Tarde Alexandre,

Gostaria de aprender um pouco sobre o elasticsearch e comprei seu livro. Porém este início para quem não é programador ficou um pouco complicado. Você tem algum mini tutorial de como fazer o set up inicial para poder usar os comandos do Curl?

Obrigado

**Comment by alexandreesl** [comment]
Oi, amigo! Tudo bom? Desculpe a demora para responder. Infelizmente este livro de fato é mais voltado para pessoal técnico, se você não quiser usar o curl, eu sugiro voce dar uma olhada neste programa aqui:
https://www.postman.com/
